name: Deploy Laravel Project on push
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
      node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Build for production
      run: npm run build
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          source_dir: dist
