name: Deploy Laravel Project on push
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 14

        - name: Install dependencies
          run: npm ci

        - name: Build for production
          run: npm run build

        - name: Deploy to cPanel
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            server: ${{ secrets.ftp_server }}
            username: ${{ secrets.ftp_username }}
            password: ${{ secrets.ftp_password }}
            source_dir: dist
